#!/usr/bin/env python3
"""
plot_wheelie_csv.py

Reads the CSV generated by wheelie_mujoco_direct_simple_csv.py and makes plots.
This file is intentionally separate from the MuJoCo simulation file.

Run:
    python3 plot_wheelie_csv.py
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt


CSV_PATH = Path(__file__).with_name("wheelie_mujoco_log_rls.csv")
# CSV_PATH = Path(__file__).with_name("wheelie_mujoco_log.csv")
SAVE_FIG = True
FIG_PATH = Path(__file__).with_name("wheelie_mujoco_plots.png")


def load_csv(csv_path: Path):
    if not csv_path.exists():
        raise FileNotFoundError(
            f"CSV file not found: {csv_path}\n"
            "Run wheelie_mujoco_direct_simple_csv.py first."
        )
    return np.genfromtxt(csv_path, delimiter=",", names=True)


def main():
    data = load_csv(CSV_PATH)

    t = data["time"]
    pitch_deg = data["pitch_deg"]
    raw_pitch_deg = data["raw_pitch_deg"]
    pitch_ref_deg = data["pitch_ref_deg"]
    pitch_dot = data["pitch_dot"]
    tau = data["tau_cmd"]
    ctrl = data["ctrl_cmd"]
    x = data["x"]
    v = data["x_dot"]

    omega_dot_measured = data["omega_dot_filtered"]
    omega_dot_rls = data["omega_dot_rls"]*-1
    rls_error = data["rls_error"]

    print("Loaded:", CSV_PATH)
    print(f"Final pitch: {pitch_deg[-1]:.2f} deg")
    print(f"Final x:     {x[-1]:.3f} m")
    print(f"Final v:     {v[-1]:.3f} m/s")
    print(f"Max pitch:   {np.max(pitch_deg):.2f} deg")
    print(f"Min pitch:   {np.min(pitch_deg):.2f} deg")

    fig, axs = plt.subplots(5, 1, sharex=True, figsize=(10, 10))

    # Same main plot as your original NMPC script: pitch and reference.
    axs[0].plot(t, pitch_deg, label="controller pitch")
    #axs[0].plot(t, raw_pitch_deg, linestyle=":", label="raw MuJoCo pitch")
    axs[0].plot(t, pitch_ref_deg, linestyle="--", label="pitch reference")
    axs[0].set_ylabel("pitch [deg]")
    axs[0].grid(True)
    axs[0].legend()

    # Torque command from NMPC.
    axs[1].plot(t, tau, label="tau_cmd")
    axs[1].plot(t, ctrl, linestyle="--", label="MuJoCo ctrl")
    axs[1].set_ylabel("command")
    axs[1].grid(True)
    axs[1].legend()

    # Forward velocity, like your original script.
    axs[2].plot(t, v, label="x_dot")
    axs[2].set_ylabel("velocity [m/s]")
    axs[2].grid(True)
    axs[2].legend()

    axs[3].plot(t, omega_dot_measured, label="measured omega_dot")
    axs[3].plot(t, omega_dot_rls, linestyle="--", label="RLS omega_dot")
    axs[3].plot(t, rls_error, linestyle=":", label="RLS error")
    axs[3].set_ylabel("omega_dot [rad/s^2]")
    axs[3].grid(True)
    axs[3].legend()

    # Extra useful debug plot.
    axs[4].plot(t, pitch_dot, label="pitch_dot")
    axs[4].plot(t, x, label="x")
    axs[4].set_xlabel("time [s]")
    axs[4].set_ylabel("omega / x")
    axs[4].grid(True)
    axs[4].legend()

    fig.suptitle("MuJoCo Wheelie NMPC Results")
    fig.tight_layout()

    if SAVE_FIG:
        fig.savefig(FIG_PATH, dpi=200)
        print("Saved figure:", FIG_PATH)

    plt.show()


if __name__ == "__main__":
    main()
