# configuration files for folders and file names

files:
    mujoco_model: "planar_monstertruck.xml"
    ini_data_file: "mujoco_random_obstacles.npz"
    # ini_data_file: "dataset_ep0060.npz"
    # ini_data_file: "dataset_ep0082.npz"

models: 
    xpos: "svgp_dynamics_xpos_delta.pt"
    xpos_dot: "svgp_dynamics_xpos_dot_delta.pt"
    pitch: "svgp_dynamics_pitch_delta.pt"
    pitch_dot: "svgp_dynamics_pitch_dot_delta.pt"

gp:
    input: ["xpos", "xpos_dot", "pitch", "pitch_dot", "u"]
    output: ["xpos", "xpos_dot", "pitch", "pitch_dot"]
    sample_time_dt: 0.1
    type_of_data: "delta"
    kernel: "RQ"
    batch_size: 1000
    num_inducing: 1000
    learning_rate: 0.03
    iterations: 300